### PR TITLE
libwebp 1.2.4

### PR DESCRIPTION
**Pull request by skupr-anaconda**
Changelog: https://chromium.googlesource.com/webm/libwebp/+/refs/tags/v1.2.4/ChangeLog and https://chromium.googlesource.com/webm/libwebp/+/refs/tags/v1.2.4/NEWS
CMakeLists.txt: https://chromium.googlesource.com/webm/libwebp/+/refs/tags/v1.2.4/CMakeLists.txt

Actions:
1. Update `bld.bat`:
- `Hack for winres.h being called winresrc.h on VS2008` was moved from `libwebp-base-feedstock` and added here.
- other updated from conda-forge recipe
2. Update `build.sh`: added `--disable-static`
3. Fix run_exports with `{{ pin_compatible('libwebp-base') }}`
4. Fix host selectors and use `libwebp-base {{ version }}.*`.
5. Add `libwebp-base {{ version }}.*` to run.
6. Update `test/commands` from conda-forge

### CODE REVIEW

**Comment by skupr-anaconda** [comment]
`win-64` is waiting for `libwebp-base` https://github.com/AnacondaRecipes/libwebp-base-feedstock/pull/4, others uploaded from the temporary  [sk_test](https://anaconda.org/sk_test/libwebp-base/files) channel

**Review by varlackc — COMMENTED** [review]
The package seems to be failing on `win-64` we might need to see if we can build on concourse for the missing architectures.

**Review by katietz — APPROVED** [review]
thanks

**Review by cbouss — APPROVED** [review]
LGTM

**Review by varlackc — APPROVED** [review]
LGTM

**Pull request merged**
